env:
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'natssuu88'
  timeout_in: 120m
  container:
    image: natsu88/ubuntu:latest
    cpu: 8
    memory: 32G

  Memuat-ccache_background_script:
     - ./script/memuat_ccache.sh
     
  Repo-pribadi_script:
     - git config --global user.name "natssuu88"
     - git config --global user.email "$EMAIL"
     - echo "$CREDENTIALS" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials

  Sinkronisasi_script:
     - ./script/sinkronisasi.sh
     
  Build-rom_script:
     - ./script/membangun.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s
     
  Upload-build_script:
     - ./script/mengemas.sh
     
